name: Release Scribe

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release Scribe
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Code
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-go@v5
        name: Setup Go
        with:
          go-version: "stable"
          cache: true

      - run: go mod tidy
        name: Get Modules

      - uses: goreleaser/goreleaser-action@v6
        name: Release Scribe
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
